[package]
name = "rs_transducers"
version = "0.0.4"
authors = ["Ben Ashford"]
license = "MIT/Apache-2.0"
repository = "https://github.com/benashford/rs-transducers"
description = "Implementation of transducers for Rust"
readme = "README.md"

[dependencies]
